# Generated by Django 2.1.7 on 2019-03-30 15:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rental_floor_plan'),
        ('ongoing', '0006_auto_20190325_1412'),
        ('buy', '0003_buy_floor_plan'),
        ('news', '0002_auto_20190325_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField(max_length=250)),
                ('img_disp', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buy.Buy')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsOngoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField(max_length=250)),
                ('img_disp', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ongoing.Ongoing')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField(max_length=250)),
                ('img_disp', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rental.Rental')),
            ],
        ),
    ]
