# Generated by Django 2.1.7 on 2019-04-15 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Buy', 'Buy'), ('Rent', 'Rent')], max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('img_disp', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('img_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('img_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('img_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('img_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('floor_plan1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('floor_plan2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('floor_plan3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('floor_plan4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('desc', models.TextField(max_length=200)),
                ('prop_Id', models.IntegerField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('prop_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('On-Hold', 'On-Hold')], max_length=20)),
                ('area', models.IntegerField()),
                ('Bedrooms', models.IntegerField()),
                ('Bath', models.IntegerField()),
                ('parking', models.CharField(max_length=40)),
                ('amen1', models.CharField(blank=True, max_length=40)),
                ('amen2', models.CharField(blank=True, max_length=40)),
                ('amen3', models.CharField(blank=True, max_length=40)),
                ('amen4', models.CharField(blank=True, max_length=40)),
                ('amen5', models.CharField(blank=True, max_length=40)),
                ('amen6', models.CharField(blank=True, max_length=40)),
                ('map_link', models.CharField(blank=True, max_length=350)),
                ('video_link', models.CharField(blank=True, max_length=250)),
                ('is_published', models.BooleanField(default=True)),
                ('sold', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
