# Generated by Django 2.1.7 on 2019-03-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongoing', '0003_auto_20190318_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoing',
            name='area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ongoing',
            name='img_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ongoing',
            name='parking',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ongoing',
            name='status',
            field=models.CharField(choices=[('Sold', 'Sold'), ('On-Hold', 'On-Hold'), ('Available', 'Available')], max_length=20),
        ),
    ]
