# Generated by Django 2.1.7 on 2019-03-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongoing', '0004_auto_20190320_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoing',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('On-Hold', 'On-Hold')], max_length=20),
        ),
    ]
