# Generated by Django 2.1.7 on 2019-03-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190320_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
