# Generated by Django 2.1.7 on 2019-04-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('display_Image', models.ImageField(height_field='960px', upload_to='photos/%Y/%m/%d/', width_field='1920px')),
                ('ceo_img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
