# Generated by Django 2.1.7 on 2019-04-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='display_Image',
        ),
        migrations.AddField(
            model_name='about',
            name='display_img',
            field=models.ImageField(height_field='960px', null=True, upload_to='photos/%Y/%m/%d/', width_field='1920px'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ceo_img',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
