# Generated by Django 2.1.7 on 2019-03-22 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('img_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('img_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('img_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('img_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('desc', models.TextField(max_length=200)),
                ('prop_Id', models.IntegerField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('prop_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('On-Hold', 'On-Hold')], max_length=20)),
                ('area', models.IntegerField()),
                ('Bedrooms', models.IntegerField()),
                ('Bath', models.IntegerField()),
                ('parking', models.CharField(max_length=40)),
                ('is_published', models.BooleanField(default=True)),
                ('sold', models.BooleanField(default=False)),
                ('rent', models.CharField(max_length=20)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
